# config/patches/uservolume.yaml
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/sdb'
  minSize: 10GB
  maxSize: 10GB
